name: 490-run
channels:
- menpo
- asmeurer
- conda-forge
- defaults
dependencies:
- harfbuzz=0.9.35=6
- pango=1.36.8=3
- asn1crypto=0.24.0=py35_0
- backcall=0.1.0=py_0
- backports=1.0=py35_1
- backports.functools_lru_cache=1.5=py35_0
- blas=1.1=openblas
- bleach=2.1.3=py_0
- ca-certificates=2018.4.16=0
- certifi=2018.4.16=py35_0
- cffi=1.11.5=py35_0
- click=6.7=py_1
- cryptography=2.2.1=py35_0
- cycler=0.10.0=py35_0
- dask-core=0.17.2=py_0
- dbus=1.11.0=0
- decorator=4.3.0=py_0
- entrypoints=0.2.3=py35_1
- eventlet=0.22.1=py_0
- expat=2.2.5=0
- flask=0.12.2=py35_0
- flask-socketio=2.9.5=py_0
- gettext=0.19.8.1=0
- glib=2.55.0=0
- gmp=6.1.2=0
- greenlet=0.4.13=py35_0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=1
- h5py=2.7.1=py35_2
- hdf5=1.10.1=2
- html5lib=1.0.1=py_0
- icu=58.2=0
- idna=2.6=py35_1
- imageio=2.3.0=py35_0
- ipykernel=4.8.2=py35_0
- ipython=6.3.1=py35_0
- ipython_genutils=0.2.0=py35_0
- itsdangerous=0.24=py_2
- jedi=0.12.0=py35_0
- jinja2=2.10=py35_0
- jpeg=9b=2
- jsonschema=2.6.0=py35_1
- jupyter=1.0.0=py_1
- jupyter_client=5.2.3=py35_0
- jupyter_console=5.2.0=py35_0
- jupyter_core=4.4.0=py_0
- libffi=3.2.1=3
- libiconv=1.15=0
- libpng=1.6.28=2
- libsodium=1.0.16=0
- libtiff=4.0.7=1
- libxcb=1.13=0
- libxml2=2.9.8=0
- markupsafe=1.0=py35_0
- mistune=0.8.3=py35_1
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py35_0
- ncurses=5.9=10
- networkx=2.1=py35_0
- notebook=5.4.1=py35_0
- olefile=0.45.1=py35_0
- openblas=0.2.20=7
- openssl=1.0.2o=0
- pandas=0.22.0=py35_0
- pandoc=2.1.3=0
- pandocfilters=1.4.2=py35_0
- parso=0.2.0=py_0
- patsy=0.5.0=py35_0
- pcre=8.41=1
- pexpect=4.5.0=py35_0
- pickleshare=0.7.4=py35_0
- pip=9.0.3=py35_0
- prompt_toolkit=1.0.15=py35_0
- ptyprocess=0.5.2=py35_0
- pycparser=2.18=py35_0
- pygments=2.2.0=py35_0
- pyopenssl=17.5.0=py35_1
- pyparsing=2.2.0=py35_0
- python=3.5.2=5
- python-dateutil=2.7.2=py_0
- python-engineio=2.0.4=py_0
- python-socketio=1.9.0=py_0
- pytz=2018.4=py_0
- pywavelets=0.5.2=py35_1
- pyzmq=17.0.0=py35_4
- qtconsole=4.3.1=py35_0
- readline=6.2=0
- scikit-image=0.13.1=py35_0
- scikit-learn=0.19.1=py35_blas_openblas_201
- scipy=1.0.1=py35_blas_openblas_200
- seaborn=0.8.1=py35_0
- send2trash=1.5.0=py_0
- setuptools=39.0.1=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.18=py35_1
- six=1.11.0=py35_1
- sqlite=3.13.0=1
- statsmodels=0.8.0=py35_0
- terminado=0.8.1=py35_0
- testpath=0.3.1=py35_0
- tk=8.5.19=2
- toolz=0.9.0=py_0
- tornado=5.0.2=py35_0
- traitlets=4.3.2=py35_0
- wcwidth=0.1.7=py35_0
- webencodings=0.5=py35_0
- werkzeug=0.14.1=py_0
- wheel=0.31.0=py35_0
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- xz=5.2.3=0
- zeromq=4.2.5=1
- zlib=1.2.11=0
- cairo=1.12.18=6
- fontconfig=2.11.1=6
- freetype=2.5.5=2
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- matplotlib=1.5.1=np111py35_0
- mkl=2017.0.3=0
- numpy=1.11.3=py35_0
- pillow=4.2.1=py35_0
- pixman=0.32.6=0
- pyqt=4.11.4=py35_4
- qt=4.8.7=4
- ipywidgets=5.1.5=py35_0
- opencv3=3.1.0=py35_0
- widgetsnbextension=1.2.3=py35_1
- pip:
  - backports.functools-lru-cache==1.5
  - dask==0.17.2
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.3
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - keras==2.1.6
  - moviepy==0.2.3.4
  - prompt-toolkit==1.0.15
  - protobuf==3.5.2.post1
  - pyyaml==3.12
  - tensorflow-gpu==1.1.0
  - theano==1.0.1
  - tqdm==4.23.0
prefix: /home/accts/vwh5/.conda/envs/car-behavioral-cloning

